### ISSUE TITLE
SEO: Improve SEO score on the SSG level

### ISSUE THREAD

**Issue by anirudhsudhir** [anna-ssg/anna#60]
Current lighthouse score for SEO is around 92%. 

- [x] Improve SEO score
- [x] Pull SEO content from Frontmatter

**Comment by polarhive** [comment]
I've added the lighthouse netlify plugin to grade our site
 
![Screenshot_2024-03-30:11:25:24](https://github.com/acmpesuecc/anna/assets/43571535/7b4a82f3-5a8c-44be-a0f0-dca3ef56967e)
